name: json_ser
description: An absolute bare-bones web app.
version: 0.0.1
homepage: https://www.example.com
#author: Alexey Zolotykh <aazolotyh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  js: any

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  webdev: any
